HumanSignal/dm2

- src/assets/icons/index.js
- src/assets/icons/plus.svg
- src/components/Common/Button/Button.js
- src/components/Common/FiltersPane.js
- src/components/Common/RadioGroup/RadioGroup.js
- src/components/Common/Tabs/Tabs.js
- src/components/Common/Tabs/Tabs.styl
- src/components/DataManager/DataManager.js
- src/components/DataManager/Toolbar/ActionsButton.js
- src/components/DataManager/Toolbar/OrderButton.js
- src/components/DataManager/Toolbar/RefreshButton.js
- src/components/DataManager/Toolbar/ViewToggle.js
- src/components/DataManager/Toolbar/instruments.js
[ext] Three dots for More button should be gray and only visible on active tab, other More buttons reveal on hover or active state
[ext] Thinner and more transparent Plus icon with rgba(0,0,0,.15) static, and rgba(0,0,0,.35) hover states
[ext] Make stats at the very right more dimmer with rgba(0,0,0,.3) text color
> Small Fixes To Dm: Tabs

- src/sdk/lsf-sdk.js
> DM for annotators

- src/sdk/api-config.js
- src/sdk/lsf-sdk.js
**list** triggers on LSF initialization
**submit** happens on draft, submit and update
> feat: DEV-1536: Add methods to submit and list user labels

- src/assets/icons/gear.svg
- src/assets/icons/index.js
- src/components/Common/Table/Table.js
- src/components/Common/Table/Table.styl
- src/components/Common/Table/utils.js
add new gear icon
add util for scrollbar width calc 
add columns button sticky to top and right of quick-view table
> Fix: DEV-790: return column button quick-view

- src/utils/feature-flags.js
> hotfix: DEV-1470: DM page navigation

- src/components/Common/Table/Table.js
- src/components/Common/Table/TableCheckbox.js
- src/components/Common/Table/TableHead/TableHead.js
- src/components/Common/Table/TableHead/TableHead.styl
- src/components/Common/Table/TableRow/TableRow.styl
- src/components/DataManager/Toolbar/LabelButton.js
- src/components/MainView/DataView/DataView.js
- src/mixins/DataStore/DataStore.js
- src/utils/feature-flags.js
- DEV-1470: DM page navigation
- Fix no tasks in the DM
- Fix tasks selection issue
- Fix tasks opening in DM
- Page number is wrong on the page reload
- DEV-2158: Label/ dropdown is obscured
> hotfix: DEV-2158: DEV-1470: 2.2.6

- src/components/Common/DatePicker/DatePicker.js
selecting different times in the datetime picker in the filter should now work as intended
> fix: DEV-706: Time picking in the DM filter

- src/sdk/lsf-sdk.js
Fixes:
- DEV-2306
- DEV-2396
- DEV-2416
- DEV-2409
> fix: DEV-2306: Error on entering deleted annotation

- src/components/MainView/DataView/DataView.js
- src/mixins/DataStore/DataStore.js
- set default value on DataStore
> fix: DEV-2170: On project open set number of tasks defined by task per page

- src/mixins/DataStore/DataStore.js
-  stopped returning to page 1 after almost any action
> fix: DEV-2153: Pagination

- src/components/Label/Label.js
- src/components/Label/Label.styl
- src/utils/feature-flags.js
- Fixes scroll behavior for the outliner view in Quick View and Label Stream
> fix: DEV-2851: Outliner updated collapse/expand UI

- src/components/CellViews/index.js
add named export for CommentAuthor
> fix: DEV-2672: Add comment authors as type of cell view

- src/components/CellViews/Annotators/Annotators.js
- src/components/CellViews/index.js
- src/components/Filters/types/List.js
null block on schema for ListFilter
> fix: DEV-2672: Comment author cell filter

- src/components/MainView/DataViewOld/Table.js
add decoration for icon columns to old table
> fix: DEV-2672: Add new column decorators to old table

- .github/workflows/eslint.yml
- package.json
> ci: SRE-400: Enable Lint for PR

- src/sdk/lsf-sdk.js
The need to change messages at `lsf` outside the `dm`. 
This fix forward the messages parameter to lsf.
You can affect `lsf` messages by `dm` parameters.
You cannot affect `lsf` messages by `dm` parameters.
N/A
This is definitely not the case.
This is definitely not the case.
N/A
N/A
lsfSDK
> feat: DEV-3928: Add messages parameter  providing into LSF options

- src/components/Common/Resizer/Resizer.styl
- src/components/Common/Table/TableHead/TableHead.js
- src/components/Common/TableOld/TableHead/TableHead.js
- [] Product design
The column resizer was rendered unusable when column drag was implimented
the column drag in datamanager 
you can resize now
it was almost impossible to resize column widths 
n/a
no
no
none
Datamanager table component
> fix: DEV-4033: fix adjustable columns data manager

- src/components/Common/Table/TableHead/TableHead.js
> fix: DEV-4033: Hotfix import issue 

- src/components/Common/SemanticSearch/SemanticSearch.js
- src/components/Common/SemanticSearch/SemanticSearch.styl
- src/components/DataManager/DataManager.js
- src/components/DataManager/Toolbar/instruments.js
- src/dev.js
- src/sdk/dm-sdk.js
- src/stores/AppStore.js
- src/stores/Tabs/tab.js
- src/utils/feature-flags.js
> feat: LOPS-12: Frontend spike - adding a new LabelOps page

- src/components/DataGroups/ImageDataGroup.js
- src/components/MainView/GridView/GridView.styl
> fix: LOPS-25: Update grid images to not be cropped

- src/stores/Tabs/store.js
- src/utils/feature-flags.js
This is just an additional fix in order for the tests to be successful
> fix: LSDV-4659: Fix hanging tab request

- src/components/CandidateTaskView/CandidateTaskView.js
- src/components/CandidateTaskView/CandidateTaskView.styl
- src/components/CandidateTaskView/index.js
- src/components/MainView/DataView/DataView.js
- src/components/MainView/DataViewOld/Table.js
> feat: LOPS-73: Candidate task frontend display UI

- src/components/CandidateTaskView/CandidateTaskView.js
- src/components/CandidateTaskView/CandidateTaskView.styl
> feat: LOPS-116: Update frontend candidate task view to show File attributes

- .github/workflows/build.yml
- .github/workflows/eslint.yml
- package.json
- webpack.config-builder.js
- yarn.lock
Currently used Node 14 is coming to its end on April 30, 2023. We're updating to the lates NodeJS LTS version as the part of scheduled maintenance cycle.
NodeJS 14 is going to be discontinued.
Updates CI env to the LTS version.
CI, Local environments
> chore: LSDV-4894: Update to NodeJS LTS

- get-build.js
- package.json
- yarn.lock
- [c32a4028d47a7294a94315e9c87694dd7193f101] #185
> fix: 1.8.0 cherrypick 2023 05 24

- src/sdk/lsf-utils.ts
- src/types/Task.ts
- src/utils/feature-flags.js
64655a9a7e84543ad8c994a22d9c26a614d9948a
> chore: 1.8.0 cherrypick 2023 05 30

- yarn.lock
> fix: LSDV-E-135: Dependabot updates

- package.json
- yarn.lock
> fix: LSDV-5249: Manual security updates

- src/components/DataManager/Toolbar/ActionsButton.js
> feat: LOPS-45: [FE] Select and export CandidateTasks to an existing Project

- src/stores/Tabs/tab_selected_items.js
> fix: LOPS-185: [FE] resolve issue affecting semantic search when selecting items then changing text in semantic search

- .github/workflows/sync-pr-ls.yml
- .github/workflows/sync-pr-lse.yml
> ci: SRE-541: Dynamic GH org name

- src/components/Common/Button/Button.js
- src/components/Common/FiltersPane.js
- src/components/Common/Form/Elements/Input/Input.js
- src/components/Common/RadioGroup/RadioGroup.js
- src/components/Common/Table/Table.js
- src/components/Common/Table/TableHead/TableHead.js
- src/components/Common/TableOld/Table.js
- src/components/DataManager/Toolbar/ActionsButton.js
- src/components/DataManager/Toolbar/ActionsButton.styl
- src/components/DataManager/Toolbar/LabelButton.js
- src/components/DataManager/Toolbar/RefreshButton.js
- src/components/DataManager/Toolbar/Toolbar.js
- src/components/DataManager/Toolbar/ViewToggle.js
- src/components/DataManager/Toolbar/instruments.js
- src/stores/Action.js
- src/utils/feature-flags.js
splitting out the new UX from the Datasets/Semantic search FF to improve separation of concerns
> feat: LOPS-280: UI changes for Data Explorer are also affecting Data Manager

- src/components/DataManager/Toolbar/ActionsButton.js
while new UX FF was off - the action button callbacks were not being used correctly
> fix: LOPS-280: UI changes for Data Explorer are also affecting Data Manager

- src/sdk/dm-sdk.js
- src/sdk/lsf-sdk.js
- src/utils/feature-flags.js
> fix: LSDV-4620-3: Fix Richtext performance and functional

- src/stores/Tabs/store.js
we need a way to allow the backend to indicate if a column is filterable
> feat: LOPS-247: Disallow Filtering my vectorized columns (image or text)

- src/components/CandidateTaskView/CandidateTaskView.js
- src/components/CandidateTaskView/CandidateTaskView.styl
- src/components/Common/Spinner.js
candidate task preview to show the content of the file instead of just the url. if .text or .txt we'll request the content and show it. other wise if its a url we'll show a link to the file. other wise show raw text
> fix: LOPS-322: [FE] Update CandidateTask preview to handle text

- yarn.lock
> ci: Fix several vulnerabilities from dependabot

- src/components/MainView/DataView/DataView.js
- src/components/MainView/DataView/DataView.styl
- src/components/MainView/DataViewOld/Table.js
- src/components/MainView/DataViewOld/Table.styl
we now force the user to wait for sync complete before user is able to semantic search or see results
> fix: LOPS-379: [FE] Search input box should be hidden and appropriate message should be displayed for non-synced datasets

- src/components/MainView/DataViewOld/Table.js
- src/components/MainView/GridViewOld/GridView.js
- src/stores/Tabs/tab.js
Grid scroll wasnt behaving correctly for both Projects and Data Discovery
> fix: DIA-548: Grid view in DD does not auto-load next records when user scrolls down

- src/mixins/DataStore/DataStore.js
the issue was only replicated locally - seems to be ok on develop and FB, but when breakage happens it causes the data explorer to break
> fix: DIA-631: [FE] if associated projects dont get sent back the data-explorer breaks

- src/stores/Tabs/tab.js
- src/stores/types.js
semantic search can now preserve thresshold which contains from/to
> feat: DIA-99: [FE] Create range slider frontend component and add to Semantic Search

- package.json
- yarn.lock
There is a problem with the version that the software is using for postcss
Update the package postcss to version 8.4.31
postcss updated to version 8.4.31
> fix: LEAP-303: Fix github vulnerabilities

- src/components/MainView/DataViewOld/Table.js
- src/sdk/lsf-sdk.js
Drafts were not being saved if you switched to another history item before leaving the task
> fix: OPTIC-113: Draft save on switch history and exit

- src/stores/Tabs/tab.js
> fix: DIA-643: [FE] max threshold 1 makes it so we cant see results for semantic search

- src/components/DataManager/Toolbar/ActionsButton.js
we want to allow propogation to have Dropdown close itself on click
> fix: DIA-706: [FE] Action menu remains open when user select 'Find similar option'

- src/components/CellViews/ProjectCell.js
- src/components/CellViews/index.js
We need to visualize which projects the dataset item has been exported to
> feat: DIA-474: [FE] add new column for DE

- src/components/CellViews/ProjectCell.js
- src/components/CellViews/index.js
associated projects on Data Explorer now link to the project directly
> feat: DIA-803: [FE] Make associated projects clickable

- src/components/Common/Table/TableHead/TableHead.js
- src/components/Common/TableOld/TableHead/TableHead.js
- src/components/MainView/DataView/DataView.js
- src/components/MainView/DataViewOld/Table.js
> chore: Cherry picked DIA-820 into release 1.11.0

- package.json
- yarn.lock
updating a dependency to address vulnerability
> fix: OPTIC-411: [lsp] Fix Follow Redirects improperly handles URLs in the url.parse() function
