src/components/Common/Button/Button.js
src/components/Common/FiltersPane.js
src/components/Common/RadioGroup/RadioGroup.js
src/components/DataManager/Toolbar/ActionsButton.js
src/components/DataManager/Toolbar/OrderButton.js
src/components/DataManager/Toolbar/RefreshButton.js
src/components/DataManager/Toolbar/ViewToggle.js
src/components/DataManager/Toolbar/instruments.js

[ext] There should always be “Tasks” button in toolbar. If no tasks are selected, it should be disabled but visible anyway
[ext] The min-width of “Tasks” button should fit at least 3 digits if it says ”N Tasks” (110px), when more digits it should resize
[ext] Both List/Grid radiogroup and Refresh button should be the same width of 110px (in other words, the same width of Tasks button)[ext] Thinner and more transparent Plus icon with rgba(0,0,0,.15) static, and rgba(0,0,0,.35) hover states
[ext] Make stats at the very right more dimmer with rgba(0,0,0,.3) text color

Small Fixes To Dm: Toolbar

---

src/components/Common/AudioPlayer/Duration.js

This can happen because of a bug in the browser, or if the server serving the audio file doesn't support range requests.

[fix] Fix crash when audio duration is Infinity

---

src/sdk/lsf-sdk.js

- fix: DEV-2098: sum lead_time for different runs (#42)

Release 2.2.0 (DEV-2098)

---

src/sdk/lsf-sdk.js
src/utils/feature-flags.js

* feat: DEV-2715: Audio v3 improvements
* initialize hydrated state to false, so the default in LSF remains true
* only setHydrated with FF set
* fix: DEV-3917: Reinit history after draft applied (#136)
Co-authored-by: hlomzik <hlomzik@gmail.com>
Co-authored-by: Nick Skriabin <767890+nicholasrq@users.noreply.github.com>

feat: DEV-2715: Audio v3 improvements (#133)

---

src/sdk/api-config.js
src/sdk/lsf-sdk.js
src/stores/DataStores/tasks.js

Task history now is stored on the backend, now you can navigate through the tasks stored on the backend on label stream clicking on the arrows.
Now the task history is stored on the backend for label stream
Task history is not stored in any place, so if you navigating through the tasks and refresh the browser you lose the task history.
NA
No
No
NA
NA

feat: LSDV-3936: Task history is stored on the backend

---

src/stores/AppStore.js

There are performance issues when requesting too many fields in the datamanager for a given project.
Reduces fields included in the results for project queries fired from polling.
This should increase performance given the requests will not have to process certain problematic fields, which were also going unneeded. 
Project TaskList

fix: LSDV-4746-1: Only include limited fields for project when polling

---

src/stores/Tabs/tab.js

The defaultWidth of the DataManager Table view when QuickView is loaded was not the correct size.
Use the css custom property of the exact menu sidebar width to set the default width of the Quickview viewable Datamanager sidebar.
QuickView

fix: LSDV-5008: Make DM default width equal to the main menu width in Quick View

---

src/sdk/lsf-utils.ts
src/types/Task.ts
src/utils/feature-flags.js

Uses the draft_created_at value as the createdDate to keep with a historical data that is consistent based on the work done. This is so the annotation tabs can be properly sorted.
`fflag_feat_back_lsdv_5035_use_created_at_from_draft_for_annotation_256052023_short`
Annotation, Draft

feat: LSDV-5035: Use created_at from draft as the annotation draft_created_at

---

src/stores/Tabs/store.js

When building up the column paths a parent can be undefined which eventually breaks everything down stream. This is not a root cause fix but a graceful handling of what is likely caused by incorrect data until we can find a root cause fix, this will at least unblock user's workflows and allow us to debug further.
DataManager, QuickView

fix: LSDV-5355: Check before using column id in DM column creation

---

src/sdk/lsf-sdk.js

https://labelstudio.aha.io/develop/features/OPTIC-7
Adds lead time from draft to lead time calculation 
lead time is accurate 
lead time is only calculated from the current session 
none
no
no

fix: OPTIC-7: Sum lead time from previous draft on annotation submission

---

src/sdk/lsf-sdk.js

An option submit/update and exit the stream to stop lead time from running on
feature
you are able to submit and not load another task and instead return to the datamanager list
if you want to take a break you would have to close the window
N/A
no
no
There are likely numerous methods for passing information to the LSF SDK. However, since we were already utilizing query parameters in the 'submit' function, it made sense to continue using this approach for passing a temporary flag to the SDK. This method is convenient because it avoids interfering with the existing chain of functions that have been scaffolded between the two stores.
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation …

feat: OPTIC-3: Enable users to submit and pause their lead time by returning to the dm list

---

webpack.config-builder.js

`EnvironmentPlugin` was used twice, plus `API_GATEWAY` is already in [.env.defaults](https://github.com/HumanSignal/dm2/blob/master/.env.defaults).
Webpack is complaining about this during build, because those values are different. So I left it only to be in ENV vars, not to be set directly in webpack config.

chore: Fix "Conflicting values" during build

---

src/sdk/lsf-sdk.js
src/stores/AppStore.js

To help keep more control with the annotator's workflow we are going to be offering more aggressive draft saving, and notification of this. However it was identified that this would have introduced a regression with regards to creating a blank draft in doing so, and thus this fix is required to allow this functionality to be enabled in full.
- `fflag_feat_optic_2_ensure_draft_saved_short`
LabelStream, QuickView

fix: OPTIC-109: Blank draft should not be created when an annotation is submitted

---

src/sdk/lsf-sdk.js

Toast messages should be displayed on save, update actions as well as draft save on leave

fix: OPTIC-124: Save and update have success/fail toast messages

---

src/components/MainView/DataView/DataView.js
src/components/MainView/DataViewOld/Table.js
src/utils/feature-flags.js

empty state when sync is in failed state should display distinct message and show a message to open storage settings
DataDiscovery data explorer

fix: DIA-667: [FE] semantic search empty state when no results exist with in selected threshold

---

src/sdk/dm-sdk.js
src/stores/AppStore.js

fix: DIA-609: Workspaces

---

src/components/DataManager/Toolbar/ActionsButton.js
src/components/DataManager/Toolbar/ActionsButton.styl
src/stores/Action.js

we dont want to allow export to project until sync is completed, but we do want to visualize the item with an indication of why its disabled

fix: DIA-736: [FE] disable add to project actions when dataset sync is not complete

---

src/stores/Tabs/store.js

since Data Explorer doesnt uses the tabs interface having default view creation and new view creation calling reload only caused the tasks endpoint to fire more times than needed leading to extra load at dataset creation

fix: DIA-640: [FE] when creating a new dataset and navigating to it tasks request will fire multiple times

---

src/mixins/DataStore/DataStore.js
src/stores/AppStore.js
src/stores/Tabs/store.js
src/stores/Tabs/tab.js
src/utils/api-proxy/index.js

api requests can now check if request is already in flight - if already in flight cancel first promise and use the new one. this prevents a race condition where second request resolves before the first causing the first to override changes applied by the second (where second one has the correct outcome due to having more up to date params)

fix: DIA-754: [FE] Search option does not reflect actual queries state

---

src/utils/bem.tsx

fix: LEAP-381: Remove excess regexp from BEM module

---

src/components/MainView/DataViewOld/Table.js
src/sdk/lsf-sdk.js

drafts were being lost when view all was selected, this change ensures they are saved and notifies the user accordingly. 

feat: OPTIC-107: Draft saving on view all

---

src/components/Common/Table/TableHead/TableHead.js
src/components/Common/TableOld/TableHead/TableHead.js
src/components/MainView/DataView/DataView.js
src/components/MainView/DataViewOld/Table.js

For purposes of Data Explorer column type selection is disallowed, Projects will work as before

feat: DIA-820: [FE] Make List type columns display as intended type with out the ability for users to change type for Data Discovery

---

src/components/CellViews/DateTimeCell.js
src/components/CellViews/StringCell.js

there was an issue where all falsey values would be treated as empty string, which is undesired. this change makes it so 0 and false will render as expected but null and undefined will be treated as empty string

fix: OPTIC-152: Uploading a text field but only 'true' is showing up not 'false'

---

src/components/DataGroups/AudioDataGroup.js
src/components/DataGroups/TextDataGroup.js

minor visual tweak to truncate text in grid view. will show a tooltip on hover to show more info about truncated text

fix: OPTIC-108: Text on grid view should be truncated

---

src/sdk/lsf-sdk.js

minor tweak to give feedback to user on successful annotation save and exiting labeling flow

fix: OPTIC-218: 'Annotation saved successfully' message is NOT displayed when user exit label stream using 'Submit and exit' option

---

src/components/Label/Toolbar/Toolbar.js
src/sdk/dm-sdk.js
src/sdk/lsf-sdk.js

Mirroring changes to LSF:
- Remove `viewingAllPredictions`
- Remove `panels`
- Remove `hydrated`
Those properties are removed in LSF, so we have to remove their usage

fix: LEAP-443: Support small changes in LSF

---

src/components/DataManager/DataManager.js
src/stores/Tabs/tab.js
src/utils/feature-flags.js

this was a predecessor to automated labeling that we started working on before DIA team became DIA team - the work was abandoned and it looks like we're moving in another direction with prompter workflow
value should be false - was a work in progress and never released
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, …

refactor: OPTIC-469: fflag_feat_front_lops_12_label_ops_ui_short removal
